In [1]:
#이름: 문재형
#학번: 2022177357

In [2]:
!pip install numpy #이미 설치되어 있음


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
a = np.arange(6)

In [7]:
a.shape

(6,)

In [5]:
a2 = a[np.newaxis, :]

In [6]:
a2.shape

(1, 6)

In [31]:
#1.배열이란?(a)

In [24]:
a1 = np.array([1,2,3,4,5,6]) #정수값이 하나의 인덱스인 1차원 정렬

In [25]:
a2 = np.array([range(7)]) #?

In [34]:
a5 = np.array([for range in range(7)]) #??

SyntaxError: invalid syntax (1304728521.py, line 1)

In [27]:
a3 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) #리스트가 하나의 인덱스인 1차원 정렬

In [28]:
print(a1[0]) #a1 정렬의 첫번째 인덱스(정수값) 호출

1


In [29]:
print(a2[0]) #a2 정렬의 첫번째 인덱스 호출

[0 1 2 3 4 5 6]


In [30]:
print(a3[0]) #a3 정렬의 첫번째 인덱스(리스트) 호출

[1 2 3 4]


In [35]:
#2.기본 배열(b)

In [138]:
b1 = np.array(1,2,3) #왜왜?? 정수는 안돼? --> 정수는 하나의 값만 즉, array(x)에서 정수x는 range(y)의 정수y와 비슷한 개념.. 길이를 의미

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [53]:
b2 = np.array([1,2,3]) #b2에 [1,2,3,]리스트를 1차원적으로 배열화해서 넣어줘

In [54]:
b2

array([1, 2, 3])

In [50]:
b3 = np.zeros(4) #b3에 '실수 0'이 4개인 리스트를 1차원적으로 배열화해서 넣어줘

In [47]:
b3

array([0., 0., 0., 0.])

In [64]:
b4 = np.ones(6) #b4에 '실수 1'이 6개인 리스트를 1차원적으로 배열화해서 넣어줘

In [52]:
b4

array([1., 1., 1., 1., 1., 1.])

In [62]:
b5 = np.empty(6)

In [63]:
b5

array([4.63939877e-308, 5.64938534e+036, 1.78409531e+046, 4.32950182e-035,
       8.72433218e-026, 1.57234264e-063])

In [68]:
b6 = np.arange(8) #b6에 '정수'가 8개인 리스트를 1차원적으로 배열화해서 넣어줘.. 다만, 첫번째 인덱스는 0부터 시작(기본 중 기본!!!)

In [66]:
b6

array([0, 1, 2, 3, 4, 5, 6, 7])

In [78]:
b7 = np.linspace(0, 10, num=5) #b7에 '실수 0~10'까지의 수를 5등분한 리스트를 1차원적으로 배열화해서 넣어줘

In [77]:
b7

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [83]:
b8 = np.ones(2, dtype=np.int64)

In [84]:
b8

array([1, 1], dtype=int64)

In [102]:
#3.요소 추가, 제거 및 정렬(c,d)

In [87]:
c = np.array([2,1,6,4,8,5,7,3])

In [88]:
c

array([2, 1, 6, 4, 8, 5, 7, 3])

In [94]:
c1 = np.sort(c) #Numpy님~ c배열을 순서대로 알아서 정렬해줘

In [91]:
c1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
c2 = np.argsort(c)

In [96]:
c2

array([1, 0, 7, 3, 5, 2, 6, 4], dtype=int64)

In [97]:
c3 = np.lexsort(c)

In [98]:
c3

0

In [192]:
c4 = np.searchsorted(c) #??

TypeError: searchsorted() missing 1 required positional argument: 'v'

In [193]:
c5 = np.partition(c) #??

TypeError: partition() missing 1 required positional argument: 'kth'

In [103]:
d1 = np.array([1,2,3,4])
d2 = np.array([5,6,7,8])

In [110]:
d3 = np.concatenate((d1,d2)) #Numpy님~ d1,2배열을 합친 d3배열을 만들어줘

In [109]:
d3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
d4 = np.array([[1,2],[3,4]])
d5 = np.array([[5,6]])

In [115]:
d6 = np.concatenate((d4,d5), axis=0) #Numpy님~ d4,5배열을 합치되, 축이 하나인 d6배열을 만들어줘

In [116]:
d6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [136]:
#4.배열의 모양과 크기(e,f)

In [123]:
e = np.array([[[0,1,2,3],
               [4,5,6,7]],
              
              [[8,9,10,11],
               [12,13,14,15]],
              
              [[16,17,18,19],
               [20,21,22,23]]])

In [128]:
e.ndim #e배열의 차원은?

3

In [129]:
e.size #e배열의 사이즈는?

24

In [130]:
e.shape #e배열의 모양(차원별 갯수)은?

(3, 2, 4)

In [139]:
f = np.arange(6)

In [140]:
f

array([0, 1, 2, 3, 4, 5])

In [144]:
#arrange(x)일 때는 x = (정수값) --> range와 비슷한 개념
#array(y)일 때는 y = (리스트 항목) --> 값 그 자체

In [148]:
f1 = f.reshape(3,2) #f배열을 3개의 행과 2개의 열로 구성된 배열로 만들어줘

In [147]:
f1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [153]:
f2 = np.reshape(f, newshape=(1,6), order='C')

In [154]:
f2

array([[0, 1, 2, 3, 4, 5]])

In [155]:
#5.1배열의 차원 추가(g)

In [156]:
g = np.arange(7)

In [157]:
g

array([0, 1, 2, 3, 4, 5, 6])

In [159]:
g.shape # g배열의 1차원엔 7개 인덱스

(7,)

In [175]:
g1 = g[np.newaxis, :] #g배열의 '열' 차원 추가

In [161]:
g1

array([[0, 1, 2, 3, 4, 5, 6]])

In [162]:
g1.shape

(1, 7)

In [174]:
g2 = g[:, np.newaxis] #g배열의 '행' 차원 추가

In [170]:
g2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [176]:
g2.shape

(7, 1)

In [188]:
g01 = np.expand_dims(g, axis=1) #g배열의 인덱스 위치 '1'에 축을 추가

In [189]:
g01

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [190]:
g01.shape

(7, 1)

In [186]:
g02 = np.expand_dims(g, axis=0) #g배열의 인덱스 위치 '0'에 축을 추가

In [180]:
g02

array([[0, 1, 2, 3, 4, 5, 6]])

In [182]:
g02.shape

(1, 7)

In [204]:
#6.인덱싱 및 슬라이싱 (h,i)

In [194]:
h = np.array([1,2,3])

In [199]:
h[0] #h배열의 1번째 인덱스는?

1

In [196]:
h[1] #h배열의 2번째 인덱스는?

2

In [200]:
h[0:2] #h배열의 1번째부터 2개까지 인덱스는?

array([1, 2])

In [202]:
h[1:] #h배열의 2번째부터 인덱스는?

array([2, 3])

In [203]:
h[-2:] #h배열의 반대 2번째부터 인덱스는?

array([2, 3])

In [205]:
i = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [208]:
print(i[i<5])

[1 2 3 4]


In [219]:
five_down = ( i<5) #'five_down'이라는 식을 먼저 정의

In [217]:
print(i[five_down])

[1 2 3 4]


In [223]:
div_by_2 = i[i%2==0] #'div_by_2'이라는 식을 먼저 정의

In [222]:
print(div_by_2)

[ 2  4  6  8 10 12]


In [252]:
#7. 기존 데이터에서 배열을 만드는 방법 (j,k,l)

In [228]:
j = np.array([1,2,3,4,5,6,7,8,9,10])

In [231]:
JJ = j[3:8] #j 배열을 4번째 인덱스부터

In [230]:
JJ

array([4, 5, 6, 7, 8])

In [233]:
j1 = np.array([[1,1],
              [2,2]])
j2 = np.array([[3,3],
              [4,4]])

In [234]:
j1

array([[1, 1],
       [2, 2]])

In [235]:
j2

array([[3, 3],
       [4, 4]])

In [237]:
np.vstack((j1,j2)) #j1, j2 배열을 수직으로 쌓아줘

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [239]:
np.hstack((j1,j2)) #j1, j2 배열을 수평으로 쌓아줘

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [243]:
k = np.arange(1, 25).reshape(2,12)

In [244]:
k

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [248]:
np.hsplit(k,3) #k배열을 동일한 모양의 배열 3개로 분할해줘

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [249]:
np.hsplit(k, (3,4)) #k배열을 세 번째와 네 번째 열 이후에 분할해줘

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [254]:
l = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [262]:
l1 = l[0, :] #l1은 l배열을 슬라이스한

In [259]:
l1

array([1, 2, 3, 4])

In [267]:
l1[0] = 99 #l1의 첫번쨰 인덱스를 99로 바꿔줘 --> l의 첫번째 인덱스도 바뀜

In [261]:
l1

array([99,  2,  3,  4])

In [265]:
l

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [269]:
l2 = l.copy() #copy 매서드로 카피

In [307]:
#8. 기본 배열 연산 (m, n, o, p)

In [284]:
m = np.array([1,2])

In [285]:
n = np.ones(2)

In [305]:
m

array([1, 2])

In [306]:
n

array([1, 1])

In [288]:
n = np.ones(2, dtype=int) #정수로 바꿔줘~

In [292]:
o1 = m + n

In [293]:
o1

array([2, 3])

In [294]:
o2 = m - n

In [295]:
o2

array([0, 1])

In [296]:
o3 = m * m

In [297]:
o3

array([1, 4])

In [303]:
o4 = m / m

In [304]:
o4

array([1., 1.])

In [312]:
p1 = np.array([1,2,3,4])

In [313]:
p1.sum()

10

In [315]:
p2 = np.array([[1,1], [2,2]])

In [316]:
p2.sum()

6

In [320]:
p2.sum(axis=0) #행축의 값을 합해줘 (axis=0은 행 축을 의미)

array([3, 3])

In [321]:
p2.sum(axis=1) #열축의 값을 합해줘 (axis=1은 열 축을 의미)

array([2, 4])

In [322]:
#9. Broadcasting (q, r)

In [323]:
q = np.array([1.0, 2.0])

In [325]:
q * 1.6

array([1.6, 3.2])

In [327]:
q.max()

2.0

In [328]:
q.min()

1.0

In [331]:
q.sum()

3.0

In [332]:
r = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [333]:
r.sum()

4.8595784

In [334]:
r.max()

0.82485143

In [335]:
r.min()

0.05093587

In [337]:
r.min(axis=0) #각 행을 기준으로 최소값을 알려줘

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [339]:
r.max(axis=1) #각 열을 기준으로 최대값을 알려줘

array([0.5510652 , 0.55645993, 0.82485143])

In [340]:
#10. 행렬생성 (s, t)

In [341]:
s = np.array([[1,2], [3,4], [5,6], [7,8]])

In [343]:
s[0,1]

2

In [344]:
s[0:1]

array([[1, 2]])

In [345]:
s[0, 0:1]

array([1])

In [346]:
s.max()

8

In [347]:
s.min()

1

In [349]:
s.sum()

36

In [350]:
s.max(axis=1)

array([2, 4, 6, 8])

In [351]:
s.min(axis=0)

array([1, 2])

In [355]:
t1 = np.ones(3)

In [356]:
t1

array([1., 1., 1.])

In [357]:
t2 = np.zeros(3)

In [358]:
t2

array([0., 0., 0.])

In [362]:
t3 = np.random.default_rng()

In [364]:
t3.random(3)

array([0.54266284, 0.52950188, 0.20000777])

In [369]:
#11. 난수생성

In [368]:
t3.integers(5, size=(2, 4))

array([[1, 4, 3, 0],
       [0, 3, 3, 3]], dtype=int64)

In [389]:
#12. 고유힌 아이템과 갯수 (u)

In [374]:
u = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [375]:
u

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [381]:
u1 = np.unique(u) #고유한(중복되지 않은) 아이템만 추출

In [382]:
u1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [386]:
u1, u2 = np.unique(u, return_index=True)

In [387]:
u2

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64)

In [388]:
u1, u3 = np.unique(u, return_counts=True)

In [402]:
#13. 행렬 전치 및 형태 변경 (v)

In [391]:
v = np.array([[1,2], [3,4], [5,6]])

In [392]:
v

array([[1, 2],
       [3, 4],
       [5, 6]])

In [393]:
v1 = v.reshape(2,3)

In [394]:
v1

array([[1, 2, 3],
       [4, 5, 6]])

In [395]:
v2 = v1.reshape(3,2)

In [396]:
v2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [397]:
v3 = v.transpose()

In [398]:
v3

array([[1, 3, 5],
       [2, 4, 6]])

In [400]:
v4 = v.T

In [401]:
v4

array([[1, 3, 5],
       [2, 4, 6]])

In [404]:
#14. 배열을 뒤집는 방법 (w)

In [413]:
w = np.arange(1,9) #==array([1,2,3,4,5,6,7,8])

In [412]:
w

array([1, 2, 3, 4, 5, 6, 7, 8])

In [414]:
w1 = np.flip(w)

In [415]:
w1

array([8, 7, 6, 5, 4, 3, 2, 1])

In [417]:
#15. 다차원 배열 재구성 및 평면화 (x)

In [420]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [421]:
x1 = x.flatten()

In [422]:
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [423]:
x1[0] = 99

In [424]:
x1

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [425]:
x2 = x.ravel()

In [426]:
x2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [427]:
x2[0] = 88

In [428]:
x2

array([88,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])